### ISSUE TITLE
Could not find module `Sound.Tidal.Context'

### ISSUE THREAD

**Issue by davehorner** [tidalcycles/tidal-chocolatey#3]
`choco install tidalcycles`
```
Chocolatey v0.10.15
Installing the following packages:
tidalcycles
By installing you accept licenses for the packages.
TidalCycles v0.9.9 already installed.

```

No problem with super.
```
include("SuperDirt")
SuperDirt.start
```
>SuperDirt: listening to Tidal on port 57120

`C:\working\music> cabal update`
> Downloading the latest package list from hackage.haskell.org
> To revert to previous state run:
>     cabal v2-update 'hackage.haskell.org,2020-04-15T01:18:28Z'

`C:\working\music> cabal new-install tidal --lib`
> Resolving dependencies...
> Up to date

`C:\working\music>cabal --version`

> cabal-install version 3.0.0.0
> compiled using version 3.0.0.0 of the Cabal library

`C:\working\music>ghci`

> GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
> Prelude> import Sound.Tidal.Context
> 
> <no location info>: error:
>     Could not find module `Sound.Tidal.Context'
>     It is not a module in the current program, or in any known package.

what am i missing?

**Comment by yaxu** [comment]
That's strange. Could it be that you have more than one core of haskell and therefore ghci installed?

**Comment by davehorner** [comment]
Ya, strange stuff.  all the ghci calls seem to go to this one in chocolatey.

I'm trying to use the tidalcycles vscode plugin I get this output: (i understand it would have no hope of working without this import working, but wanted to provide that detail too):
Error: Error: write EPIPE
Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

My lack of haskell knowledge is showing...

C:\working> which ghci
/c/ProgramData/chocolatey/lib/ghc/tools/ghc-8.8.3/bin/ghci

# where ghci
C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.8.3\bin\ghci.exe

C:\working> which cabal
/c/ProgramData/chocolatey/bin/cabal

no ghci in wsl; I let win10 do its 30min search and it shows only the same ghci.
![image](https://user-images.githubusercontent.com/140924/79644774-1a455a00-8179-11ea-8679-50a767b8d5e7.png)

I'll keep playing with it; cabal thinks its there.

**Comment by davehorner** [comment]
cabal install Cabal cabal-install
```
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - Cabal-3.0.2.0 (lib) (requires download & build)
...yada yada yada ..
Starting     cabal-install-3.2.0.0 (all, legacy fallback)
Building     cabal-install-3.2.0.0 (all, legacy fallback)
Installing   cabal-install-3.2.0.0 (all, legacy fallback)
Completed    cabal-install-3.2.0.0 (all, legacy fallback)
C:\Users\DAVID~1.HOR\AppData\Local\Temp\cabal-install.-41412\dist-newstyle\tmp\src-41412\cabal-install-3.2.0.0\dist\setup\setup.exe: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:DeleteFile "\\\\?\\C:\\Users\\DAVID~1.HOR\\AppData\\Local\\Temp\\cabal-install.-41412\\dist-newstyle\\tmp\\src-41412\\cabal-install-3.2.0.0\\dist\\setup\\setup.exe": permission denied (Access is denied.)
```

Which was a strange way to end the thing.
cabal install Cabal cabal-install
```Resolving dependencies...
Up to date
Copying 'cabal.exe'```

it again thinks it's up to date; but not really.
cabal --version
```cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library
```

but it does lead to an interesting new output:  
cabal new-install tidal --lib
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: directory-1.3.6.1 (user goal)
[__1] next goal: ghc (user goal)
[__1] rejecting: ghc-8.8.3/installed-8.8... (conflict: directory==1.3.6.1, ghc
=> directory==1.3.6.0/installed-1.3...)
[__1] rejecting: ghc-8.6.5, ghc-8.6.4, ghc-8.6.1, ghc-8.4.4, ghc-8.4.3,
ghc-8.4.1, ghc-8.2.2, ghc-8.2.1 (constraint from user target requires ==8.8.3)
[__1] fail (backjumping, conflict set: directory, ghc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: directory, ghc
```
oh joy.  it's this machine.  I've had success on others.

**Comment by yaxu** [comment]
In retrospect, `cabal v1-install tidal` might have worked..

But closing this for now, please reopen if it's still an issue

**Comment by dobke** [comment]
I am currently facing the same issues. Still having problems to set up my tidal cycles setup.
SuperCollider seems to work fine, at least I am getting the output: _listening to Tidal on port 57120_
After initializing a new tidal-file in Atom i tried to boot the tidal package and get this:
_t> *
: error:

Could not find module `Sound.Tidal.Context’*
It is not a module in the current program, or in any known package._

So I assume that tital was not installed correctly. Instead I tried to set up tidal with the stack stack install tidal
seems to work, but still getting the `Sound.Tidal.Context’ error.
Any ideas?
thank you

**Comment by yaxu** [comment]
Did you try `cabal v1-install tidal` ?
Or you can go into the tidalcycles package settings in atom to use the stack version you've installed.

**Comment by dobke** [comment]
> Did you try `cabal v1-install tidal` ?
> Or you can go into the tidalcycles package settings in atom to use the stack version you've installed.

Thank you for your fast response. `cabal v1-install tidal` dosn't work. I am still getting these network errors. But with the stack version I got around. Everything works perfectly so far
Thank you again!

**Comment by maheshj01** [comment]
That means tidal is not installed try running 

```
cabal update
cabal install tidal --lib
```

In case you do not have cabal install it using brew 

```
brew install cabal-install
```

Following the above worked in my case
